# Generated by Django 6.1 on 2026-09-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DPO', 'DPO'), ('REFERENT', 'Référent')], default='COMPLIDO', max_length=100),
        ),
    ]
