# Generated by Django 6.1 on 2026-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('COMPLIDO', 'Complido'), ('TROPICO', 'Tropico Assurance'), ('BIGOBANK', 'Big Bank')], default='COMPLIDO', max_length=100),
        ),
    ]
