# Generated by Django 6.1 on 2026-09-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de données',
                'verbose_name_plural': 'Catégories de données',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de personnes concernées',
                'verbose_name_plural': 'Catégories de personnes concernées',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Base légale',
                'verbose_name_plural': 'Bases légales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Type d'opération",
                'verbose_name_plural': "Types d'opération",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Opération du traitement',
                'verbose_name_plural': 'Opérations du traitement',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingSecurityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Prévue'), ('PARTIAL', 'Partiellement mise en œuvre'), ('IMPLEMENTED', 'Mise en œuvre'), ('NOT_APPLICABLE', 'Non applicable')], default='PLANNED', max_length=20)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mesure de sécurité du traitement',
                'verbose_name_plural': 'Mesures de sécurité du traitement',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('INTERNAL', 'Interne'), ('EXTERNAL', 'Externe'), ('PUBLIC', 'Autorité publique')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ORGANIZATIONAL', 'Organisationnelle'), ('TECHNICAL', 'Technique'), ('PHYSICAL', 'Physique')], max_length=20)),
            ],
            options={
                'verbose_name': 'Mesure de sécurité',
                'verbose_name_plural': 'Mesures de sécurité',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subprocessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Sous-traitant',
                'verbose_name_plural': 'Sous-traitants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('subpurpose', models.CharField(blank=True, max_length=255)),
                ('description_purpose', models.TextField(blank=True)),
                ('retention_period', models.CharField(blank=True, max_length=255)),
                ('international_transfer', models.BooleanField(default=False)),
                ('aipd_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_categories', models.ManyToManyField(blank=True, related_name='data_processings', to='personal_data_processing.datacategory')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_processings', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['name'],
            },
        ),
    ]
