# Generated by Django 6.1 on 2026-09-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data_processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_processings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='data_subject_categories',
            field=models.ManyToManyField(blank=True, related_name='data_processings', to='personal_data_processing.datasubjectcategory'),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='legal_basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_processings', to='personal_data_processing.legalbasis'),
        ),
        migrations.AddField(
            model_name='processingoperation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_operations', to='personal_data_processing.operationtype'),
        ),
        migrations.AddField(
            model_name='processingoperation',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_operations', to='personal_data_processing.dataprocessing'),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='operations',
            field=models.ManyToManyField(blank=True, related_name='data_processings', through='personal_data_processing.ProcessingOperation', to='personal_data_processing.operationtype'),
        ),
        migrations.AddField(
            model_name='processingsecuritymeasure',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_security_measures', to='personal_data_processing.dataprocessing'),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='data_processings', to='personal_data_processing.recipient'),
        ),
        migrations.AddField(
            model_name='processingsecuritymeasure',
            name='security_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_security_measures', to='personal_data_processing.securitymeasure'),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='security_measures',
            field=models.ManyToManyField(blank=True, related_name='data_processings', through='personal_data_processing.ProcessingSecurityMeasure', to='personal_data_processing.securitymeasure'),
        ),
        migrations.AddField(
            model_name='dataprocessing',
            name='subprocessors',
            field=models.ManyToManyField(blank=True, related_name='data_processings', to='personal_data_processing.subprocessor'),
        ),
        migrations.AddConstraint(
            model_name='processingoperation',
            constraint=models.UniqueConstraint(fields=('processing', 'operation_type'), name='unique_processing_operation'),
        ),
        migrations.AddConstraint(
            model_name='processingsecuritymeasure',
            constraint=models.UniqueConstraint(fields=('processing', 'security_measure'), name='unique_processing_security_measure'),
        ),
    ]
