# Generated by Django 6.1 on 2026-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data_processing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprocessing',
            name='entity',
            field=models.CharField(choices=[('COMPLIDO', 'Complido'), ('TROPICO', 'Tropico Assurance'), ('BIGOBANK', 'Big Bank')], default='COMPLIDO', max_length=100),
        ),
    ]
